# Generated by Django 2.2.7 on 2020-01-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_surname', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=50)),
                ('student_year', models.IntegerField()),
                ('student_gpa', models.FloatField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_tatalcredit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('subject_nameTH', models.CharField(max_length=100)),
                ('subject_nameEN', models.CharField(max_length=100)),
                ('subject_detail', models.CharField(max_length=500)),
                ('subject_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_year', models.IntegerField()),
                ('plan_semester', models.IntegerField()),
                ('plan_gps', models.FloatField()),
                ('plan_no', models.IntegerField()),
                ('plan_totalcredit', models.IntegerField()),
                ('plan_remark', models.CharField(max_length=500)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
