# Generated by Django 2.2.7 on 2020-01-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_tatalcredit',
            new_name='student_totalcredit',
        ),
        migrations.AddField(
            model_name='detail',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='planner',
            name='plan_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_have_pre_subject',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='planner',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PreSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_subject_id', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject')),
            ],
        ),
    ]
