# Generated by Django 2.2.7 on 2020-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200109_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
