# Generated by Django 2.2.7 on 2020-02-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200202_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='presubject',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Planner',
        ),
        migrations.DeleteModel(
            name='PreSubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
