# Generated by Django 3.0.3 on 2020-03-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200212_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(default=None, max_length=10)),
                ('Year', models.CharField(default=None, max_length=4)),
                ('Semester', models.CharField(default=None, max_length=7)),
                ('SubjectID1', models.CharField(default=None, max_length=8)),
                ('Subject1', models.CharField(default=None, max_length=50)),
                ('Grade1', models.CharField(default=None, max_length=2)),
                ('SubjectID2', models.CharField(default=None, max_length=8)),
                ('Subject2', models.CharField(default=None, max_length=50)),
                ('Grade2', models.CharField(default=None, max_length=2)),
                ('SubjectID3', models.CharField(default=None, max_length=8)),
                ('Subject3', models.CharField(default=None, max_length=50)),
                ('Grade3', models.CharField(default=None, max_length=2)),
                ('SubjectID4', models.CharField(default=None, max_length=8)),
                ('Subject4', models.CharField(default=None, max_length=50)),
                ('Grade4', models.CharField(default=None, max_length=2)),
                ('SubjectID5', models.CharField(default=None, max_length=8)),
                ('Subject5', models.CharField(default=None, max_length=50)),
                ('Grade5', models.CharField(default=None, max_length=2)),
                ('SubjectID6', models.CharField(default=None, max_length=8)),
                ('Subject6', models.CharField(default=None, max_length=50)),
                ('Grade6', models.CharField(default=None, max_length=2)),
                ('SubjectID7', models.CharField(default=None, max_length=8)),
                ('Subject7', models.CharField(default=None, max_length=50)),
                ('Grade7', models.CharField(default=None, max_length=2)),
                ('SubjectID8', models.CharField(default=None, max_length=8)),
                ('Subject8', models.CharField(default=None, max_length=50)),
                ('Grade8', models.CharField(default=None, max_length=2)),
                ('SubjectID9', models.CharField(default=None, max_length=8)),
                ('Subject9', models.CharField(default=None, max_length=50)),
                ('Grade9', models.CharField(default=None, max_length=2)),
                ('SubjectID10', models.CharField(default=None, max_length=8)),
                ('Subject10', models.CharField(default=None, max_length=50)),
                ('Grade10', models.CharField(default=None, max_length=2)),
                ('GPAX', models.CharField(default=None, max_length=4)),
                ('GPA', models.CharField(default=None, max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_picture',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
