# Generated by Django 3.0.3 on 2020-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200321_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='credit1',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit10',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit2',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit3',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit4',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit5',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit6',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit7',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit8',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='history',
            name='credit9',
            field=models.CharField(default=3, max_length=1),
        ),
    ]
