# Generated by Django 2.2.7 on 2020-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_credit',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
