# Generated by Django 2.2.7 on 2020-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_category_category_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_credit',
            field=models.CharField(max_length=3),
        ),
    ]
