# Generated by Django 3.0.3 on 2020-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20200218_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_detail',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
