# Generated by Django 3.0.3 on 2020-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20200218_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='addsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=1)),
                ('addsubject_date', models.CharField(max_length=10)),
                ('addsubject_startime', models.TimeField()),
                ('addsubject_endtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SA_year', models.CharField(max_length=4)),
                ('SA_semster', models.CharField(max_length=50)),
                ('SA_id', models.CharField(max_length=8)),
                ('SA_nameTH', models.CharField(max_length=100)),
                ('SA_nameEN', models.CharField(max_length=100)),
                ('SA_credit', models.CharField(max_length=1)),
                ('SA_hour', models.CharField(max_length=1)),
            ],
        ),
    ]
