# Generated by Django 3.0.3 on 2020-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_addsubject_subjectactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_detail',
        ),
    ]
