# Generated by Django 3.0.3 on 2020-03-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_remove_subject_subject_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('user_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_ID', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=200)),
                ('Subject_credit', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Create_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.IntegerField(default=0)),
                ('Time_start', models.TimeField(blank=True, null=True)),
                ('Time_close', models.TimeField(blank=True, null=True)),
                ('day_id', models.IntegerField(default=0)),
                ('Username', models.CharField(default=0, max_length=200)),
                ('Subject_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Subject')),
            ],
        ),
    ]
