# Generated by Django 3.0.3 on 2020-03-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_create_plan_plan_subject_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_plan',
            name='Subject_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Subject_plan'),
        ),
    ]
