# Generated by Django 3.0.3 on 2020-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20200321_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_plan',
            name='Subject_ID',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
